name: Create envfile

on: [ push ]

jobs: 
  create_env_file_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          touch .env
          echo ENGINE_API_KEY=${{ secrets.GH_TOKEN }} >> .env
