name: Create envfile

on: [ push ]

jobs: 
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GITHUB_LOGIN: "sania-dsouza"
